const hre = require("hardhat");
const { ethers } = hre;
const fs = require("fs");
const path = require("path");

/**
 * Deploy CapFund.sol to the configured network.
 * After deployment, writes the contract address to:
 * - deployed_address.txt  (for reference)
 * - ../frontend/src/utils/deployedAddress.js  (imported by the frontend)
 * - ../frontend/src/utils/abi.js  (ABI auto-synced from artifacts)
 */
async function main() {
  const [deployer] = await ethers.getSigners();
  const networkName = hre.network.name;

  console.log("=".repeat(60));
  console.log("🚀 Deploying CapDAO contract...");
  console.log("   Network :", networkName);
  console.log("   Deployer:", deployer.address);

  const balance = await ethers.provider.getBalance(deployer.address);
  console.log("   Balance :", ethers.formatEther(balance), "ETH");
  console.log("=".repeat(60));

  // Deploy
  const CapFund = await ethers.getContractFactory("CapFund");
  const capFund = await CapFund.deploy();
  await capFund.waitForDeployment();

  const contractAddress = await capFund.getAddress();
  console.log("✅ CapDAO deployed at:", contractAddress);

  // ── Write deployed address to a plain text file ─────────────────────────
  const contractsDir = path.resolve(__dirname, "..");
  fs.writeFileSync(
    path.join(contractsDir, "deployed_address.txt"),
    contractAddress
  );

  // ── Sync address to frontend ─────────────────────────────────────────────
  const frontendUtilsDir = path.resolve(__dirname, "../../frontend/src/utils");
  
  if (fs.existsSync(frontendUtilsDir)) {
    // Write address
    fs.writeFileSync(
      path.join(frontendUtilsDir, "deployedAddress.js"),
      `// Auto-generated by deploy.js — do not edit manually\nexport const CONTRACT_ADDRESS = "${contractAddress}";\n`
    );

    // Copy ABI from hardhat artifacts
    const artifactPath = path.join(
      contractsDir,
      "artifacts/contracts/CapFund.sol/CapFund.json"
    );
    
    if (fs.existsSync(artifactPath)) {
      const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
      fs.writeFileSync(
        path.join(frontendUtilsDir, "abi.js"),
        `// Auto-generated by deploy.js — do not edit manually\nexport const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)};\n`
      );
      console.log("✅ ABI synced to frontend/src/utils/abi.js");
    } else {
      console.warn(`⚠️ ABI artifact not found at ${artifactPath}`);
    }

    console.log("✅ Contract address synced to frontend/src/utils/deployedAddress.js");
  } else {
    console.warn(
      "⚠️  Frontend utils dir not found — set VITE_CONTRACT_ADDRESS manually in frontend/.env"
    );
  }

  // ── Dynamic Network Instructions ─────────────────────────────────────────
  console.log("\n📋 Next steps:");
  
  if (networkName === "localhost") {
    console.log("   1. Open MetaMask → Add/Switch to Hardhat Local (chain 31337, http://127.0.0.1:8545)");
    console.log("   2. Import Account #0 private key into MetaMask to get 10,000 test ETH");
  } else {
    console.log("   1. Open MetaMask → Add Monad Testnet (chain 10143, https://testnet-rpc.monad.xyz/)");
    console.log("   2. Get testnet MON from https://faucet.monad.xyz/");
    console.log("   5. Explorer: https://testnet.monadvision.com/address/" + contractAddress);
  }
  
  console.log("   3. Frontend address auto-synced to frontend/src/utils/deployedAddress.js");
  console.log("   4. Start the frontend: cd ../frontend && npm run dev");
  console.log("=".repeat(60));
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});